### ISSUE TITLE
Indicator of maximum capacity breaks sometimes

### ISSUE THREAD

**Issue by gnarea** [relaycorp/relaynet-courier-android#109]
0.9 GB available before the sync with people:

![Screenshot_2020-05-29-11-26-34](https://user-images.githubusercontent.com/369863/83251714-ead73380-a1a1-11ea-93e2-d47765f8caff.png)

But after receiving 91 MB, the max capacity allocated becomes 96 MB:

![Screenshot_2020-05-29-11-40-08](https://user-images.githubusercontent.com/369863/83251799-10643d00-a1a2-11ea-8fb2-1ff7509f06d1.png)

Note I didn't change the settings. I can reproduce this with a Nexus 4.

Logs around the time this happened:

```
05-29 11:35:15.456 24256-24271/tech.relaycorp.courier I/art: Background partial concurrent mark sweep GC freed 51573(3MB) AllocSpace objects, 303(28MB) LOS objects, 35% free, 29MB/45MB, paused 1.373ms total 156.447ms
05-29 11:35:15.741 24256-24256/tech.relaycorp.courier I/StandaloneCoroutine: deliverCargo next aa3b0aa5-5bd1-4e73-bf35-e4e18657d389
05-29 11:35:15.984 24256-24256/tech.relaycorp.courier I/StandaloneCoroutine: deliverCargo next ack aa3b0aa5-5bd1-4e73-bf35-e4e18657d389
05-29 11:35:16.843 24256-24271/tech.relaycorp.courier I/art: Background partial concurrent mark sweep GC freed 47477(3MB) AllocSpace objects, 282(24MB) LOS objects, 32% free, 33MB/49MB, paused 1.281ms total 106.271ms
05-29 11:35:16.869 24256-24256/tech.relaycorp.courier I/StandaloneCoroutine: deliverCargo next 2bcc9466-9d01-4a7e-9e35-243328d6d2a0
05-29 11:35:17.059 24256-24271/tech.relaycorp.courier I/art: Background partial concurrent mark sweep GC freed 13517(833KB) AllocSpace objects, 73(6MB) LOS objects, 21% free, 58MB/74MB, paused 1.495ms total 102.304ms
05-29 11:35:17.065 24256-24256/tech.relaycorp.courier I/StandaloneCoroutine: deliverCargo no space available for 2bcc9466-9d01-4a7e-9e35-243328d6d2a0
05-29 11:35:17.065 24256-24256/tech.relaycorp.courier I/StandaloneCoroutine: deliverCargo closing with error
05-29 11:35:17.157 24256-25640/tech.relaycorp.courier I/connections: Transport failed
    java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
        at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:592)
        at libcore.io.IoBridge.recvfrom(IoBridge.java:568)
        at java.nio.SocketChannelImpl.readImpl(SocketChannelImpl.java:342)
        at java.nio.SocketChannelImpl.read(SocketChannelImpl.java:304)
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: android.system.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
        at libcore.io.Posix.recvfromBytes(Native Method)
        at libcore.io.Posix.recvfrom(Posix.java:177)
        at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:245)
        at libcore.io.IoBridge.recvfrom(IoBridge.java:565)
        at java.nio.SocketChannelImpl.readImpl(SocketChannelImpl.java:342) 
        at java.nio.SocketChannelImpl.read(SocketChannelImpl.java:304) 
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) 
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133) 
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) 
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) 
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) 
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615) 
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578) 
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) 
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) 
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) 
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) 
        at java.lang.Thread.run(Thread.java:818) 
05-29 11:39:00.589 24256-24271/tech.relaycorp.courier I/art: Background partial concurrent mark sweep GC freed 65795(3MB) AllocSpace objects, 247(33MB) LOS objects, 30% free, 35MB/51MB, paused 1.251ms total 147.108ms
05-29 11:39:03.797 24256-24256/tech.relaycorp.courier I/StandaloneCoroutine: deliverCargo next e41bb8d4-ca3e-4feb-99f0-3710765dcc1a
05-29 11:39:04.034 24256-24256/tech.relaycorp.courier I/StandaloneCoroutine: deliverCargo no space available for e41bb8d4-ca3e-4feb-99f0-3710765dcc1a
05-29 11:39:04.034 24256-24256/tech.relaycorp.courier I/StandaloneCoroutine: deliverCargo closing with error
05-29 11:39:07.036 24256-26503/tech.relaycorp.courier W/NettyServerHandler: Stream Error
    io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 1
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.shouldIgnoreHeadersOrDataFrame(DefaultHttp2ConnectionDecoder.java:596)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:239)
        at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:422)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
        at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:174)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1518)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1267)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1314)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by sdsantos** [comment]
Haven't been able to reproduce this issue. The max is dependent not only on the max configured, but also on the actual available storage on device, whichever is less. Is the Nexus 4 a emulator, or could it have ran out of space?

**Comment by gnarea** [comment]
I'm using a physical device and I don't think it's running out of space because the courier app is the only app I use there. Let me see if I can reproduce it again.

**Comment by gnarea** [comment]
I can't reproduce it again :man_shrugging: Let's close this and reopen it if it happens again.
