### ISSUE TITLE
Receiving invalid cargo crashes the app

### ISSUE THREAD

**Issue by gnarea** [relaycorp/relaynet-courier-android#128]
We're certainly validating the incoming cargo and refusing any invalid cargo, but the way we refuse that cargo is causing an uncaught exception.

If you run this test against an actual running instance of the app, it'll crash:

https://github.com/relaycorp/relaynet-courier-android/blob/1b2d55830156cdd289622cedaf1b8ed17c0c822c/relaynet-cogrpc-jvm/src/test/java/tech/relaycorp/relaynet/cogrpc/client/CogRPCClientTest.kt#L68

Logs:

```
2020-06-10 17:41:36.563 7866-7894/tech.relaycorp.courier I/UndispatchedCoroutine: Server started
2020-06-10 17:41:47.342 7866-7928/tech.relaycorp.courier I/nService$deliverCargo$1: deliverCargo complete
2020-06-10 17:41:47.361 7866-7866/tech.relaycorp.courier I/StandaloneCoroutine: deliverCargo next c9429bd8-bb1b-4746-ad51-80e3d53a3c34
2020-06-10 17:41:47.366 7866-7866/tech.relaycorp.courier W/StoreMessage: Malformed Cargo received: Serialization is too short to contain format signature
2020-06-10 17:41:47.369 7866-7866/tech.relaycorp.courier I/StandaloneCoroutine: deliverCargo invalid or malformed cargo c9429bd8-bb1b-4746-ad51-80e3d53a3c34
2020-06-10 17:41:47.369 7866-7866/tech.relaycorp.courier I/StandaloneCoroutine: deliverCargo closing with error
2020-06-10 17:41:47.394 7866-7866/tech.relaycorp.courier E/AndroidRuntime: FATAL EXCEPTION: main
    Process: tech.relaycorp.courier, PID: 7866
    java.lang.IllegalStateException: call already closed
        at com.google.common.base.Preconditions.checkState(Preconditions.java:511)
        at io.grpc.internal.ServerCallImpl.closeInternal(ServerCallImpl.java:209)
        at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:202)
        at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:371)
        at tech.relaycorp.cogrpc.server.CogRPCConnectionService$deliverCargo$1$onCompleted$1.invokeSuspend(CogRPCConnectionService.kt:60)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by sdsantos** [comment]
Something interesting happened on that log. There's a `deliverCargo complete` before the `deliverCargo invalid or malformed cargo`. That means the client closed the connection before getting an ack or an error. Although that does not seem a common scenario, is definitely something that should not crash the app.

**Comment by sdsantos** [comment]
> deliverCargo complete

My bad, `deliverCargo complete` is from the client. But I'm still trying to reproduce the issue correctly in a test.
