### ISSUE TITLE
App intermittently crashes when stopping sync with users on Android 5

### ISSUE THREAD

**Issue by gnarea** [relaycorp/relaynet-courier-android#146]
The app can crash after pressing the button to stop synchronising with users:

![ezgif-4-b25b3f13f647](https://user-images.githubusercontent.com/369863/87222506-fa829400-c36b-11ea-909d-1915d7940de6.gif)

I stopped that after synchronising with the current version of the Android Gateway.

I I didn't manage to get the logs when that happened and I can't reproduce it reliably, but I've found this in the logs after stopping the sync (without the app crashing):

```
07-11 11:32:48.709 3271-3271/tech.relaycorp.courier I/art: Explicit concurrent mark sweep GC freed 85986(4MB) AllocSpace objects, 17(544KB) LOS objects, 38% free, 25MB/41MB, paused 1.007ms total 178.635ms
07-11 11:32:48.987 3271-3271/tech.relaycorp.courier I/art: Explicit concurrent mark sweep GC freed 24225(1542KB) AllocSpace objects, 2(328KB) LOS objects, 39% free, 23MB/38MB, paused 824us total 73.126ms
07-11 11:32:49.060 3271-3271/tech.relaycorp.courier I/art: Explicit concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 39% free, 23MB/38MB, paused 824us total 68.121ms
07-11 11:32:49.110 3271-3271/tech.relaycorp.courier I/Choreographer: Skipped 35 frames!  The application may be doing too much work on its main thread.
```

`Choreographer: Skipped 35 frames!  The application may be doing too much work on its main thread` may be hint of what's going on.

**Comment by gnarea** [comment]
I've managed to make the app crash by stopping the sync **before** the first user connected. I'm not sure if this is the same root cause, so it may be a 2nd bug. Here's the logs:

```
07-11 11:52:07.267 6463-6463/tech.relaycorp.courier I/CogRPCServer: Server stopped
07-11 11:52:07.386 6463-6463/tech.relaycorp.courier I/art: Explicit concurrent mark sweep GC freed 79120(4MB) AllocSpace objects, 7(224KB) LOS objects, 39% free, 24MB/40MB, paused 1.312ms total 117.656ms
07-11 11:52:07.666 6463-6463/tech.relaycorp.courier I/art: Explicit concurrent mark sweep GC freed 19004(1312KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 23MB/39MB, paused 1.251ms total 84.846ms
07-11 11:52:07.726 6463-6463/tech.relaycorp.courier I/art: Explicit concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 40% free, 23MB/39MB, paused 1.007ms total 60.308ms
07-11 11:52:07.768 6463-6463/tech.relaycorp.courier E/StrictMode: class tech.relaycorp.courier.ui.sync.people.PeopleSyncActivity; instances=2; limit=1
    android.os.StrictMode$InstanceCountViolation: class tech.relaycorp.courier.ui.sync.people.PeopleSyncActivity; instances=2; limit=1
        at android.os.StrictMode.setClassInstanceLimit(StrictMode.java:1)
07-11 11:52:07.768 6463-6463/tech.relaycorp.courier W/System.err: StrictMode VmPolicy violation with POLICY_DEATH; shutting down.
```

**Comment by gnarea** [comment]
I've just experienced this issue again on a Nexus 4 (Android 5):

```
I/UndispatchedCoroutine: Server started
I/StandaloneCoroutine: deliverCargo next 5cc8afc5-d37d-445d-af23-31c6c0dd36fd
I/art: Background partial concurrent mark sweep GC freed 19517(1157KB) AllocSpace objects, 77(3MB) LOS objects, 32% free, 33MB/49MB, paused 1.800ms total 113.077ms
I/StandaloneCoroutine: deliverCargo next f7541450-ee69-4b6b-8b0e-a04620c6216e
I/StandaloneCoroutine: deliverCargo next 65fc2a77-0958-4154-be0e-7726c366384e
I/StandaloneCoroutine: deliverCargo next 2d3cb4fd-4f33-4fbb-8d01-6f6f2dd534e0
I/StandaloneCoroutine: deliverCargo next cb831320-3fc1-4b41-9a6e-34c17d96e941
I/art: Background partial concurrent mark sweep GC freed 33193(1269KB) AllocSpace objects, 33(11MB) LOS objects, 31% free, 35MB/51MB, paused 1.037ms total 105.295ms
I/StandaloneCoroutine: deliverCargo next ack 5cc8afc5-d37d-445d-af23-31c6c0dd36fd
I/StandaloneCoroutine: deliverCargo next ack f7541450-ee69-4b6b-8b0e-a04620c6216e
I/StandaloneCoroutine: deliverCargo next ack 65fc2a77-0958-4154-be0e-7726c366384e
I/StandaloneCoroutine: deliverCargo next ack cb831320-3fc1-4b41-9a6e-34c17d96e941
I/StandaloneCoroutine: deliverCargo next ack 2d3cb4fd-4f33-4fbb-8d01-6f6f2dd534e0
I/nService$deliverCargo$1: deliverCargo complete
I/StandaloneCoroutine: collectCargo completed empty
D/OpenGLRenderer: endAllStagingAnimators on 0xb7f35778 (RippleDrawable) with handle 0xb7cda578
I/CogRPCServer: Server stopped
I/art: Explicit concurrent mark sweep GC freed 39898(1915KB) AllocSpace objects, 30(8MB) LOS objects, 36% free, 27MB/43MB, paused 1.129ms total 114.817ms
I/art: Explicit concurrent mark sweep GC freed 2121(78KB) AllocSpace objects, 0(0B) LOS objects, 36% free, 27MB/43MB, paused 1.251ms total 70.898ms
I/art: Explicit concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 36% free, 27MB/43MB, paused 1.098ms total 71.570ms
E/StrictMode: class tech.relaycorp.courier.ui.sync.people.PeopleSyncActivity; instances=2; limit=1
    android.os.StrictMode$InstanceCountViolation: class tech.relaycorp.courier.ui.sync.people.PeopleSyncActivity; instances=2; limit=1
        at android.os.StrictMode.setClassInstanceLimit(StrictMode.java:1)
W/System.err: StrictMode VmPolicy violation with POLICY_DEATH; shutting down.
I/Process: Sending signal. PID: 12224 SIG: 9
```

That happened after the client finished the sync and I pressed "stop" on the courier app.

**Comment by sdsantos** [comment]
Just to note this is a StrictMode error and it will not affect the production app. It happens because it is detecting 2 PeopleSyncActivity instances existing at the same time, not sure why.

**Comment by gnarea** [comment]
Good to know! That certainly demotes the priority of this issue. Any chance this can grow beyond 2 instances and start causing actual issues in production? Presumably so, since we don't know the root cause, right?

BTW, I can reproduce this fairly consistently now: I've noticed it tends to happen when I clear the app data, do a sync with users and then stop the server as soon as the sync completes. Is there any logging/debugging we can do to fix this?

**Comment by sdsantos** [comment]
@gnarea I bet it never gets over 2 instances, and even having 2 instances is a temporary situation before one gets destroyed. Can't think of any extra logging right now. Usually we try to figure out a way to make it happen consistently, and then start taking things out until we figure out the cause.
