### ISSUE TITLE
Reinstate instrumented tests with Android 5 and 6 on Firebase Test Lab

### ISSUE THREAD

**Issue by gnarea** [relaycorp/relaynet-courier-android#535]
As discussed on https://github.com/relaycorp/relaynet-courier-android/pull/521#issuecomment-1185441611, we had to remove these two Android versions from the test matrix on Firebase Test Lab because we couldn't figure out why the tests were breaking there and we'd already spent a lot of time debugging it.

The app still works on real devices so this issue seems to be limited to the test environment.

**Comment by sdsantos** [comment]
Findings so far, when running tests locally with emulators. Only the `PrivateSyncTest#privateSync` test fails on both API 21 and 23. But the reasons vary:

API 21

Device crashes with `Fatal signal 11 (SIGSEGV), code 1, fault addr 0x28 in tid 5368 (DefaultDispatch)``

API 23

```
java.lang.IncompatibleClassChangeError: tech.relaycorp.relaynet.cogrpc.CargoDelivery
at dalvik.system.DexFile.defineClassNative(Native Method)
at dalvik.system.DexFile.defineClass(DexFile.java:226)
at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
at dalvik.system.DexPathList.findClass(DexPathList.java:338)
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
at tech.relaycorp.relaynet.cogrpc.CargoRelayGrpc.getDeliverCargoMethod(CargoRelayGrpc.java:38)
at tech.relaycorp.relaynet.cogrpc.CargoRelayGrpc.getServiceDescriptor(CargoRelayGrpc.java:327)
at tech.relaycorp.relaynet.cogrpc.CargoRelayGrpc.bindService(CargoRelayGrpc.java:264)
at tech.relaycorp.relaynet.cogrpc.CargoRelayGrpc$CargoRelayImplBase.bindService(CargoRelayGrpc.java:150)
at io.grpc.internal.ServerImplBuilder.addService(ServerImplBuilder.java:143)
at io.grpc.internal.ServerImplBuilder.addService(ServerImplBuilder.java:57)
at io.grpc.internal.AbstractServerImplBuilder.addService(AbstractServerImplBuilder.java:93)
at io.grpc.internal.AbstractServerImplBuilder.addService(AbstractServerImplBuilder.java:48)
at tech.relaycorp.cogrpc.server.CogRPCServer$start$3.invokeSuspend(CogRPCServer.kt:63)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

We've had some `IncompatibleClassChangeError` issues in the past with GRPC and Protobuf. I tried matching versions and also updating the core desugaring library, but with no luck yet.

We may want to enable instrumented tests on those APIs but disable that test in particular until we come up with a solution.

---

The same code seems to run fine outside of the instrumented tests.

**Comment by sdsantos** [comment]
@gnarea working fine when running the same code on Android 5 and 6 emulators.
