### ISSUE TITLE
Slider seems to break on Android 5.0

### ISSUE THREAD

**Issue by gnarea** [relaycorp/relaynet-courier-android#70]
CI is breaking because the robo tests under Android 5.0 are failing with:

```
java.lang.IllegalStateException: Slider value must be greater or equal to valueFrom, and lower or equal to valueTo
     FATAL EXCEPTION: Thread-1101
Process: tech.relaycorp.courier, PID: 19052
java.lang.IllegalStateException: Slider value must be greater or equal to valueFrom, and lower or equal to valueTo
	at com.google.android.material.slider.Slider.validateValues(Slider.java:517)
	at com.google.android.material.slider.Slider.validateConfigurationIfDirty(Slider.java:530)
	at com.google.android.material.slider.Slider.calculateTicksCoordinates(Slider.java:1329)
	at com.google.android.material.slider.Slider.onSizeChanged(Slider.java:1322)
	at android.view.View.sizeChange(View.java:15627)
	at android.view.View.setFrame(View.java:15600)
	at android.view.View.layout(View.java:15516)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1734)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1588)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
	at android.view.View.layout(View.java:15520)
	at android.view.ViewGroup.layout(ViewGroup.java:4870)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:575)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15520)
	at android.view.ViewGroup.layout(ViewGroup.java:4870)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1734)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1588)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
	at android.view.View.layout(View.java:15520)
	at android.view.ViewGroup.layout(ViewGroup.java:4870)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1996)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
	at android.view.View.layout(View.java:15520)
	at android.view.ViewGroup.layout(ViewGroup.java:4870)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:575)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15520)
	at android.view.ViewGroup.layout(ViewGroup.java:4870)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1734)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1588)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
	at android.view.View.layout(View.java:15520)
	at android.view.ViewGroup.layout(ViewGroup.java:4870)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:575)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15520)
	at android.view.ViewGroup.layout(ViewGroup.java:4870)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1734)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1588)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
	at android.view.View.layout(View.java:15520)
	at android.view.ViewGroup.layout(ViewGroup.java:4870)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:575)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15520)
	at android.view.ViewGroup.layout(ViewGroup.java:4870)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2128)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1882)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1087)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6040)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:793)
	at android.view.Choreographer.doCallbacks(Choreographer.java:606)
	at android.view.Choreographer.doFrame(Choreographer.java:575)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:779)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at androidx.test.espresso.base
```

See: https://console.firebase.google.com/project/relaynet-courier/testlab/histories/bh.c82b7d21521a430d/matrices/4873315408842423881/executions/bs.45184622ec5f3c97/issues

This is the commit that triggered that build, but I can't imagine that caused the error and all the other devices continue to work: https://github.com/relaycorp/relaynet-courier-android/commit/ce2bc48b3d12df3c016755dc81bf6304f329d98b

Sergio, would you mind having a look when you get a chance?

**Comment by gnarea** [comment]
Actually, looking at the logs, this regression was introduced in #64
